import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { RootState } from "../../../store/store";

export function Home() {

    const some = useSelector((state: RootState) => state.ops.some)
    useEffect(() => {
        console.log(some)
    }, [])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='opa'>opa</div>
            <Link data-testid="link" href={'/some'}>some</Link>
        </div>
    )
}