import Head from "next/head";
import Link from "next/link";

export function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='opa'>opa</div>
            <Link data-testid="link" href={'/some'}>some</Link>
        </div>
    )
}